INSERT INTO t_card VALUES ('Ajani, Adversary of Tyrants', 'White', 'Legendary Planeswalker - Ajani', 'Core Set 2019');
INSERT INTO t_card VALUES ('Benalish Marshal', 'White', 'Creature - Human Knight', 'Dominaria');
INSERT INTO t_card VALUES ('Dauntless Bodyguard', 'White', 'Creature - Human Knight', 'Dominaria');
INSERT INTO t_card VALUES ('Skymarch Aspirant', 'White', 'Creature - Vampire Soldier', 'Rivals of Ixalan');
INSERT INTO t_card VALUES ('Snubhorn Sentry', 'White', 'Creature - Dinosaur', 'Rivals of Ixalan');
INSERT INTO t_card VALUES ('Tithe Taker', 'White', 'Creature - Human Soldier', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Venerated Loxodon', 'White', 'Creature - Elephant Cleric', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Adanto Vanguard', 'White', 'Creature - Vampire Soldier', 'Ixalan');
INSERT INTO t_card VALUES ('Baffling End', 'White', 'Enchantment', 'Rivals of Ixalan');
INSERT INTO t_card VALUES ('Conclave Tribunal', 'White', 'Enchantment', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('History of Benalia', 'White', 'Enchantment - Saga', 'Dominaria');
INSERT INTO t_card VALUES ('Legion\'s Landing', 'White', 'Legendary Enchantment', 'Ixalan');
INSERT INTO t_card VALUES ('Glacial Fortress', 'Colorless', 'land', 'Ixalan');
INSERT INTO t_card VALUES ('Hallowed Fountain', 'Colorless', 'Land - Plains Island', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Plains', 'Colorless', 'Basic Land - Plains', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Disdainful Stroke', 'Blue', 'Instant', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Tocatli Honor Guard', 'White', 'Creature - Human Soldier', 'Ixalan');
INSERT INTO t_card VALUES ('Island', 'Colorless', 'Basic Land - Island', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Spell Pierce', 'Blue', 'Instant', 'Ixalan');
INSERT INTO t_card VALUES ('Negate', 'Blue', 'Instant', 'Rivals of Ixalan');
INSERT INTO t_card VALUES ('Unbreakable Formation', 'White', 'Instant', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Merfolk Trickster', 'Blue', 'Creature - Merfolk Wizard', 'Dominaria');
INSERT INTO t_card VALUES ('Siren Stormtamer', 'Blue', 'Creature - Siren Pirate Wizard', 'Ixalan');
INSERT INTO t_card VALUES ('Tempest Djinn', 'Blue', 'Creature - Djinn', 'Dominaria');
INSERT INTO t_card VALUES ('Mist-Cloaked Herald', 'Blue', 'Creature - Merfolk Warrior', 'Core Set 2019');
INSERT INTO t_card VALUES ('Chart a Course', 'Blue', 'Sorcery', 'Ixalan');
INSERT INTO t_card VALUES ('Dive Down', 'Blue', 'Instant', 'Ixalan');
INSERT INTO t_card VALUES ('Essesnce Capture', 'Blue', 'Instant', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Opt', 'Blue', 'Instant', 'Dominaria');
INSERT INTO t_card VALUES ('Wizard\'s Retort', 'Blue', 'Instant', 'Dominaria');
INSERT INTO t_card VALUES ('Curious Obsession', 'Blue', 'Enchantment - Aura', 'Rivals of Ixalan');
INSERT INTO t_card VALUES ('Entrancing Melody', 'Blue', 'Sorcery', 'Ixalan');
INSERT INTO t_card VALUES ('Exlusion Mage', 'Blue', 'Creature - Human Wizard', 'Core Set 2019');
INSERT INTO t_card VALUES ('Surge Mare', 'Blue', 'Creature - Horse Fish', 'Core Set 2019');
INSERT INTO t_card VALUES ('Transmogrifying Wand', 'Colorless', 'Artifact', 'Core Set 2019');
INSERT INTO t_card VALUES ('Deep Freeze', 'Blue', 'Enchantment Aura', 'Dominaria');
INSERT INTO t_card VALUES ('Jace, Cunning Castaway', 'Blue', 'Legendary Planeswalker - Jace', 'Ixalan');
INSERT INTO t_card VALUES ('Teferi, Hero of Dominaria', 'Multicolored - White Blue', 'Legendary Planeswalker - Teferi', 'Dominaria');
INSERT INTO t_card VALUES ('Karn, Scion of Urza', 'Colorless', 'Legendary Planeswalker - Karn', 'Dominaria');
INSERT INTO t_card VALUES ('Thought Erasure', 'Multicolored - Blue Black', 'Sorcery', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Kaya\'s Wrath', 'Multicolored - White Black', 'Sorcery', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Cry of the Carnarium', 'Black', 'Sorcery', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Moment of Craving', 'Black', 'Instant', 'Rivals of Ixalan');
INSERT INTO t_card VALUES ('Cast Down', 'Black', 'Instant', 'Dominaria');
INSERT INTO t_card VALUES ('Vraska\'s Contempt', 'Black', 'Instant', 'Ixalan');
INSERT INTO t_card VALUES ('Chemister\'s Insight', 'Blue', 'Instant', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Mortify', 'Multicolored - White Black', 'Instant', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Absorb', 'Multicolored - White Blue', 'Instant', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Search for Azcanta', 'Blue', 'Legendary Enchantment', 'Ixalan');
INSERT INTO t_card VALUES ('The Eldest Reborn', 'Black', 'Enchantment - Saga', 'Dominaria');
INSERT INTO t_card VALUES ('Isolated Chapel', 'Colorless', 'Land', 'Dominaria');
INSERT INTO t_card VALUES ('Godless Shrine', 'Colorless', 'Land - Plains Swamp', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Drowned Catacomb', 'Colorless', 'Land', 'Ixalan');
INSERT INTO t_card VALUES ('Watery Grave', 'Colorless', 'Land - Island Swamp', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Swamp', 'Colorless', 'Basic Land - Swamp', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Thief of Sanity', 'Multicolored - Blue Black', 'Creature - Specter', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Hostage Taker', 'Multicolored - Blue Black', 'Creature - Human Pirate', 'Ixalan');
INSERT INTO t_card VALUES ('Lyra Dawnbringer', 'White', 'Legendary Create - Angel', 'Dominaria');
INSERT INTO t_card VALUES ('Duress', 'Black', 'Sorcery', 'Core Set 2019');
INSERT INTO t_card VALUES ('Kaya, Orzhov Usurper', 'Multicolored - White Black', 'Legendary Planeswalker - Kaya', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Hydroid Krasis', 'Multicolored - Green Blue', 'Creature - Jellyfish Hydra Beast', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Blink of an Eye', 'Blue', 'Instant', 'Dominaria');
INSERT INTO t_card VALUES ('Growth Spiral', 'Multicolored - Green Blue', 'Instant', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Nexus of Fate', 'Blue', 'Instant', 'Core Set 2019');
INSERT INTO t_card VALUES ('Precognitive Perception', 'Blue', 'Instant', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Root Snare', 'Green', 'Instant', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Sinister Sabotage', 'Blue', 'Instant', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Wilderness Reclamation', 'Green', 'Enchantment', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Breeding Pool', 'Colorless', 'Land - Forest Island', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Forest','Colorless', 'Basic Land - Forest', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Hinterland Harbor', 'Colorless', 'Land', 'Dominaria');
INSERT INTO t_card VALUES ('Memorial to Genius', 'Colorless', 'Land', 'Dominaria');
INSERT INTO t_card VALUES ('Simic Guildgate', 'Colorless', 'Land - Gate', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Atzocan Archer', 'Green', 'Creature - Human Archer', 'Ixalan');
INSERT INTO t_card VALUES ('Biogenic Ooze', 'Green', 'Creature - Ooze', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Crushing Canopy', 'Green', 'Instant', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Druid of the Cowl', 'Green', 'Creature - Elf Druid', 'Core Set 2019');
INSERT INTO t_card VALUES ('Incubation Druid', 'Green', 'Creature - Elf Druid', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Nezahal, Primal Tide', 'Blue', 'Legendary Creature - Elder Dinosaur', 'Rivals of Ixalan');
INSERT INTO t_card VALUES ('Diamond Mare', 'Colorless', 'Artifact Creature - Horse', 'Core Set 2019');
INSERT INTO t_card VALUES ('Faerie Duelist', 'Blue', 'Creature - Faerie Rogue', 'Ravnica Allegiance');
INSERT INTO t_card VAlUES ('Sleep', 'Blue', 'Sorcery', 'Core Set 2019');
INSERT INTO t_card VALUES ('Fanatical Firebrand', 'Red', 'Creature - Goblin Pirate', 'Rivals of Ixalan');
INSERT INTO t_card VALUES ('Ghitu Lavarunner', 'Red', 'Creature - Human Wizard', 'Dominaria');
INSERT INTO t_card VALUES ('Runaway Steam-Kin', 'Red', 'Creature - Elemental', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Viashino Pyromancer', 'Red', 'Creature - Viashino Wizard', 'Core Set 2019');
INSERT INTO t_card VALUES ('Goblin Chainwhirler', 'Red', 'Creature - Goblin Warrior', 'Dominaria');
INSERT INTO t_card VALUES ('Light Up the Stage', 'Red', 'Sorcery', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Shock', 'Red', 'Instant', 'Core Set 2019');
INSERT INTO t_card VALUES ('Lightning Strike', 'Red', 'Instant', 'Core Set 2019');
INSERT INTO t_card VALUES ('Wizard\'s Lightning', 'Red', 'Instant', 'Dominaria');
INSERT INTO t_card VALUES ('Experimental Frenzy', 'Red', 'Enchantment', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Mountain', 'Red', 'Basic Land - Mountain', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Stomping Ground', 'Colorless', 'Land - Mountain Forest', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Rootbound Crag', 'Colorless', 'Land', 'Ixalan');
INSERT INTO t_card VALUES ('Lava Coil', 'Red', 'Sorcery', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Cindervines', 'Multicolored - Red Green', 'Enchantment', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Collision // Colossus', 'Multicolored - Red Green', 'Instant', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Treasure Map', 'Colorless', 'Artifact', 'Ixalan');
INSERT INTO t_card VALUES ('Dire Fleet Daredevil', 'Red', 'Creature - Human Pirate', 'Rivals of Ixalan');
INSERT INTO t_card VALUES ('Ral, Izzet Viceroy', 'Multicolored - Blue Red', 'Legendary Planeswalker - Ral', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Arclight Phoenix', 'Red', 'Creature - Phoenix', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Goblin Electromancer', 'Multicolored - Blue Red', 'Creature - Goblin Wizard', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Crackling Drake', 'Multicolored - Blue Red', 'Creature - Drake', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Tormenting Voice', 'Red', 'Sorcery', 'Core Set 2019');
INSERT INTO t_card VALUES ('Beacon Bolt', 'Multicolored - Blue Red', 'Sorcery', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Radical Idea', 'Blue', 'Instant', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Discovery // Dispersal', 'Multicolored - Blue Black', 'Sorcery // Instant', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Steam Vents', 'Colorless', 'Land - Island Mountain', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Sulfur Falls', 'Colorless', 'Land', 'Dominaria');
INSERT INTO t_card VALUES ('Blood Crypt', 'Colorless', 'Land - Swamp Mountain', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Sorcerous Spyglass', 'Colorless', 'Artifact', 'Ixalan');
INSERT INTO t_card VALUES ('Niv-Mizzet, Parun', 'Multicolored - Blue Red', 'Legendary Creature - Dragon Wizard', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Murmuring Mystic', 'Blue', 'Creature - Human Wizard', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Shivan Fire', 'Red', 'Instant', 'Instant');
INSERT INTO t_card VALUES ('Evolving Wilds', 'Colorless', 'Land', 'Rivals of Ixalan');
INSERT INTO t_card VALUES ('Hunted Witness', 'White', 'Creature - Human', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Demystify', 'White', 'Instant', 'Ixalan');
INSERT INTO t_card VALUES ('Gatebreaker Ram', 'Green', 'Creature - Sheep', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Gate Colossus', 'Colorless', 'Artifact Creature - Construct', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Banefire', 'Red', 'Sorcery', 'Core Set 2019');
INSERT INTO t_card VALUES ('Deafening Clarion', 'Multicolored - Red White', 'Sorcery', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Gates Ablaze', 'Red', 'Sorcery', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Circuitous Route', 'Green', 'Sorcery', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Guild Summit', 'Blue', 'Enchantment', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Azorius Guildgate', 'Colorless', 'Land - Gate', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Gateway Plaza', 'Colorless', 'Land - Gate', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Gruul Guildgate', 'Colorless', 'Land - Gate', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Izzet Guildgate', 'Colorless', 'Land - Gate', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Plaza of Harmony', 'Colorless', 'Land', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Selesnya Guildgate', 'Colorless', 'Land - Gate', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Mass Manipulation', 'Blue', 'Sorcery', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Emmara, Soul of the Accord', 'Multicolored - Green White', 'Legendary Creature - Elf Cleric', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Trostani Discordant', 'Multicolored - Green White', 'Legendary Creature - Dryad', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Saproling Migration', 'Green', 'Sorcery', 'Dominaria');
INSERT INTO t_card VALUES ('March of the Multitudes', 'Multicolored - Green White', 'Instant', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Flower // Flourish', 'Multicolored - Green White', 'Sorcery', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Sunpetal Grove', 'Colorless', 'Land', 'Ixalan');
INSERT INTO t_card VALUES ('Temple Garden', 'Colorless', 'Land - Forest Plains', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Kraul Harpooner', 'Green', 'Creature - Insect Warrior', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Knight of Autumn', 'Multicolored - Green White', 'Creature - Dryad Knight', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Vivien Reid', 'Green', 'Legendary Planeswalker - Vivien', 'Core Set 2019');
INSERT INTO t_card VALUES ('Huatli, Radiant Champion', 'Multicolored - Green White', 'Legendary Planeswalker - Huatli', 'Rivals of Ixalan');
INSERT INTO t_card VALUES ('Risk Factor', 'Red', 'Enchantment', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Skewer the Critics', 'Red', 'Sorcery', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Electrostatic Field', 'Red', 'Creature - Wall', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Lightning Mare', 'Red', 'Creature - Elemental Horse', 'Core Set 2019');
INSERT INTO t_card VALUES ('Fiery Cannonade', 'Red', 'Instant', 'Ixalan');
INSERT INTO t_card VALUES ('Llanowar Elves', 'Green', 'Creature - Elf Druid', 'Core Set 2019');
INSERT INTO t_card VALUES ('Merfolk Branchwalker', 'Green', 'Creaure - Merfolk Scout', 'Ixalan');
INSERT INTO t_card VALUES ('Wildgrowth Walker', 'Green', 'Creature - Elemental', 'Ixalan');
INSERT INTO t_card VALUES ('Jadelight Ranger', 'Green', 'Creature - Merfolk Scout', 'Rivals of Ixalan');
INSERT INTO t_card VALUES ('Ravenous Chupacabra', 'Black', 'Creature - Beast Horror', 'Rivals of Ixalan');
INSERT INTO t_card VALUES ('Carnage Tyrant', 'Green', 'Creature - Dinosaur', 'Ixalan');
INSERT INTO t_card VALUES ('Vraska, Relic Seeker', 'Multicolored - Black Green', 'Legendary Planeswalker - Vraska', 'Ixalan');
INSERT INTO t_card VALUES ('Find // Finality', 'Multicolored - Black Green', 'Sorcery', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Memorial to Folly', 'Colorless', 'Land', 'Dominaria');
INSERT INTO t_card VALUES ('Overgrown Tomb', 'Colorless', 'Land - Swamp Forest', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Woodland Cemetery', 'Colorless', 'Land', 'Dominaria');
INSERT INTO t_card VALUES ('Assassin\'s Trophy', 'Multicolored - Black Green', 'Instant', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Plaguecrafter', 'Black', 'Creature - Human Shamen', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Unmoored Ego', 'Multicolored - Blue Black', 'Sorcery', 'Guilds of Ravnica');
INSERT INTO t_card VALUES ('Basilica Bell-Haunt', 'Multicolored - White Black', 'Creature - Spirit', 'Ravnica Allegiance');
INSERT INTO t_card VALUES ('Rampaging Ferocidon', 'Red', 'Creature - Dinosaur', 'Ixalan');
INSERT INTO t_banned_cards VALUES (0, 'Standard', 'Rampaging Ferocidon')